[package]
name = "fast-powi"
version = "0.1.1"
categories = ["algorithms", "mathematics", "no-std"]
description = "Provides fast exponentiation for numeric types"
repository = "https://github.com/mikem8891/fast-powi"
keywords = ["math", "fast", "powi", "num"]
license = "MIT"
readme = "README.md"
edition = "2021"
rust-version = "1.82"

[lib]

[package.metadata.docs.rs]
no-deps = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
num-bigint = { version = "0.4", default-features = false, optional = true }
num-complex = { version = "0.4", default-features = false, optional = true }
num-rational = { version = "0.4", default-features = false, optional = true }
num-traits = { version = "0.2", default-features = false }

[features]
default = []
num = ["big-int", "complex", "ratio"]
big-int = ["dep:num-bigint"]
complex = ["dep:num-complex"]
ratio = ["dep:num-rational"]
