[package]
categories = ["algorithms", "mathematics"]
description = "Provides fast exponentiation for numeric types"
keywords = ["math", "fast", "powi", "power"]
license = "MIT"
name = "fast-powi"
readme = "README.md"
repository = "https://github.com/mikem8891/fast-powi"
version = "0.1.0"
edition = "2024"

[lib]

[package.metadata.docs.rs]
no-deps = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
num-bigint = "0.4.6"
num-complex = "0.4.6"
num-integer = "0.1.46"
num-rational = "0.4.2"
num-traits = "0.2.19"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false
